import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import { EventEmitter } from 'node:events';import { PassThrough } from 'node:stream';
import { browserProfileDirectory, normalizeBrowserPageConfig, renderBrowserPageHtml, runBrowserPageCollector } from '../plugins/collectors/browser-web-page/runner.mjs';
function workspace(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'browser-collector-'));fs.mkdirSync(path.join(root,'lib','collectors'),{recursive:true});t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function child(){const value=new EventEmitter();value.stdout=new PassThrough();value.stderr=new PassThrough();value.killed=false;value.kill=()=>{value.killed=true;value.emit('exit',null);};return value;}
test('浏览器来源只接受声明式动作并限制 Profile 路径',()=>{const config=normalizeBrowserPageConfig({profileId:'news-profile',clickSelector:'.more',typeSelector:'#query',typeValue:'AI',waitMilliseconds:200});assert.deepEqual(config.actions.map((item)=>item.type),['click','type','wait']);assert.throws(()=>normalizeBrowserPageConfig({profileId:'../escape'}),/kebab-case/);assert.match(browserProfileDirectory('C:/workspace','browser-web-page','profile-a'),/browser-profiles[\\/]browser-web-page[\\/]profile-a$/);assert.throws(()=>normalizeBrowserPageConfig({actions:[{type:'evaluate'}]}),/只支持/);});
test('浏览器采集子进程使用受限环境并解析标准结果',async t=>{const root=workspace(t);let options;const spawnImpl=(_command,_args,input)=>{options=input;const value=child();queueMicrotask(()=>{value.stdout.end(JSON.stringify({status:'ok',items:[{title:'A',url:'https://public.example/a'}]}));value.emit('exit',0);});return value;};const result=await runBrowserPageCollector({url:'https://public.example',profileId:'one',itemSelector:'article'},{root,dnsLookup:async()=>[{address:'93.184.216.34'}],spawnImpl});assert.equal(result.status,'ok');assert.deepEqual(Object.keys(options.env).sort(),['PATH','PUPPETEER_CACHE_DIR','PUPPETEER_EXECUTABLE_PATH','SystemRoot','TEMP','TMP'].sort());assert.equal(options.windowsHide,true);});
test('浏览器采集硬超时会终止子进程',async t=>{const root=workspace(t);let process;const spawnImpl=()=>{process=child();return process;};await assert.rejects(()=>runBrowserPageCollector({url:'https://public.example',profileId:'one',itemSelector:'article'},{root,dnsLookup:async()=>[{address:'93.184.216.34'}],spawnImpl,timeoutMs:5000}),/硬超时/);assert.equal(process.killed,true);});
test('浏览器子进程错误保留登录失效诊断码',async t=>{const root=workspace(t);const spawnImpl=()=>{const value=child();queueMicrotask(()=>{value.stderr.end(JSON.stringify({code:'AUTH_REQUIRED',message:'检测到登录页面元素'}));value.emit('exit',1);});return value;};await assert.rejects(()=>runBrowserPageCollector({url:'https://public.example',profileId:'one',itemSelector:'article'},{root,dnsLookup:async()=>[{address:'93.184.216.34'}],spawnImpl}),error=>error.code==='AUTH_REQUIRED');});
test('动态页面分析使用同一隔离 Profile 并返回渲染 HTML',async t=>{const root=workspace(t);let payload;const spawnImpl=(_command,args)=>{payload=JSON.parse(Buffer.from(args[1],'base64url').toString('utf8'));const value=child();queueMicrotask(()=>{value.stdout.end(JSON.stringify({status:'ok',html:'<article>动态内容</article>',url:'https://public.example',title:'动态页'}));value.emit('exit',0);});return value;};const result=await renderBrowserPageHtml('https://public.example',{root,dnsLookup:async()=>[{address:'93.184.216.34'}],spawnImpl});assert.equal(payload.analysisMode,true);assert.match(payload.profileDir,/browser-profiles[\\/]browser-web-page[\\/]default$/);assert.match(result.html,/动态内容/);});
