import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../lib/core/store.mjs';
import { ToolRegistry } from '../lib/tools/registry.mjs';
import { runTutorialAgentTurn, tutorialProjectAttachmentArguments } from '../lib/agent/tutorial-adapter.mjs';
import { getFactAttachment } from '../lib/agent/fact-attachments.mjs';
import { buildCustomFactSheet } from '../lib/domain/custom-fact-builder.mjs';

function projectRegistry(){const registry=new ToolRegistry();registry.register({manifest:{id:'mock-project',name:'项目读取',version:'1.0.0',capabilities:['filesystem.project.read'],riskLevel:'read-only',pathInputs:['path'],inputSchema:{type:'object',required:['path'],properties:{path:{type:'string'},options:{type:'object'}}},outputSchema:{type:'object'}},adapter:{async execute(input){return {status:'ok',data:{root:input.path,summary:'读取 1/1 个文本文件，共 18 字符',files:[{path:'README.md',size:18,excerpt:'npm run dev\n实际说明',truncated:false}],totalFiles:1,totalChars:18,truncated:false,skipped:{}},artifacts:[],warnings:[],provenance:{}};}}});return registry;}

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'tutorial-agent-')),project=path.join(root,'demo-project');fs.mkdirSync(project);const store=new Store(path.join(root,'test.db')),batch=store.createBatch({date:'2026-08-14',title:'自主写作 Agent'});t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});return {root,project,store,batch};}

test('自主写作把检测到的路径包装为项目资源 ToolCall，模型只看到相对路径',async(t)=>{const {root,project,store,batch}=fixture(t),events=[];let modelCalls=0;const gateway={config:{defaultProvider:'mock',providers:{mock:{maxOutputTokens:4096}}},async complete({messages}){modelCalls+=1;const tool=messages.find((item)=>item.role==='tool');assert.ok(tool);assert.match(tool.content,/README\.md/);assert.doesNotMatch(tool.content,new RegExp(project.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));return {callId:'tutorial-final',content:JSON.stringify({assistantReply:'项目已作为素材读取，请确认实际体验。',briefUpdates:{articleMode:'tutorial',topic:'运行演示项目',audience:'开发者',environment:'Node.js 22',points:['【素材】README 提供启动命令','【素材】项目包含运行说明','【建议】执行前检查版本'],steps:['安装依赖','运行 npm run dev']}}),model:'mock',usage:{total_tokens:12}};}};const result=await runTutorialAgentTurn({gateway,store,registry:projectRegistry(),provider:'mock',batchId:batch.id,draft:{articleMode:'tutorial'},answer:`读取 ${project}`,projectPath:project,workspaceRoot:root,onEvent:(event)=>events.push(event)});assert.equal(modelCalls,1);assert.equal(result.toolCalls,1);assert.equal(result.ready,true);assert.equal(result.projectContext.files[0].path,'README.md');assert.equal('root' in result.projectContext,false);assert.ok(events.some((event)=>event.type==='tool.completed'));const cached=getFactAttachment(store,{batchId:batch.id,capability:'filesystem.project.read',arguments:tutorialProjectAttachmentArguments(project)});assert.equal(cached.data.summary,result.projectContext.summary);});

test('项目材料不会让心得模式绕过【体验】门禁，缓存项目下一轮不重复执行',async(t)=>{const {root,project,store,batch}=fixture(t),registry=projectRegistry();let executions=0;const original=registry.execute.bind(registry);registry.execute=async(...args)=>{executions+=1;return original(...args);};const gateway={config:{defaultProvider:'mock',providers:{mock:{maxOutputTokens:4096}}},async complete(){return {callId:'experience-final',content:JSON.stringify({assistantReply:'事实表已齐备，可以创建初稿',briefUpdates:{articleMode:'experience',topic:'项目心得',audience:'开发者',thesis:'工具仍需打磨',points:['【素材】项目包含 README','【素材】有启动命令','【建议】检查版本']}}),model:'mock',usage:{}};}};const first=await runTutorialAgentTurn({gateway,store,registry,batchId:batch.id,draft:{articleMode:'experience'},projectPath:project,workspaceRoot:root});assert.equal(first.ready,false);assert.deepEqual(first.missing,['至少一条【体验】']);await runTutorialAgentTurn({gateway,store,registry,batchId:batch.id,draft:{articleMode:'experience'},projectPath:project,workspaceRoot:root});assert.equal(executions,1);});

test('自主写作生产路由只使用 Agent、复用事实附件与统一事件消费器',()=>{const route=fs.readFileSync(new URL('../lib/http/routes/candidate-routes.mjs',import.meta.url),'utf8'),client=fs.readFileSync(new URL('../public/src/views/tutorial.js',import.meta.url),'utf8'),search=fs.readFileSync(new URL('../lib/integrations/information-search.mjs',import.meta.url),'utf8');assert.match(route,/runTutorialAgentTurn/);assert.doesNotMatch(route,/runTutorialChatStream/);assert.match(route,/listConversationFactAttachments/);assert.match(search,/if \(fact\[field\]\)/);assert.match(client,/consumeAgentEvent/);});

test('创建事实表可直接复用对话阶段 URL 附件而不重复抓取',async()=>{let fetched=0;const url='https://example.com/material',fact=await buildCustomFactSheet({input:{content_type:'tutorial',topic:'示例',points:['【素材】A','【素材】B','【建议】C'],materialUrls:[url]},root:process.cwd(),materialCache:new Map([[url,{title:'缓存材料',content:'已读取正文'}]]),fetchImpl:async()=>{fetched+=1;throw new Error('不应调用');}});assert.equal(fetched,0);assert.equal(fact.materials[0].title,'缓存材料');assert.equal(fact.materials[0].status,'ok');});
