import test from 'node:test';
import assert from 'node:assert/strict';
import { MODEL_JSON_ERROR_CODES, locateJsonValue, parseModelJson, parseModelJsonWithRepair } from '../server/platform/llm/model-json.mjs';
import { repairJsonSyntaxOnly } from '../server/platform/llm/model-json-repair.mjs';

test('统一 JSON 解析剥离围栏并定位说明文字中的主对象',()=>{assert.deepEqual(parseModelJson({content:'说明如下：\n```json\n{"ok":true,"text":"} 不结束"}\n```'}),{ok:true,text:'} 不结束'});assert.equal(locateJsonValue('prefix [1,2] suffix').text,'[1,2]');});
test('length 和未闭合结构统一分类为稳定截断错误码',()=>{for(const result of [{content:'{"x":',finishReason:'stop'},{content:'{"x":1}',finishReason:'length'}])assert.throws(()=>parseModelJson(result),(error)=>error.code===MODEL_JSON_ERROR_CODES.TRUNCATED);});
test('无 JSON 与语法错误使用稳定无效输出错误码并写审计',()=>{const updates=[];assert.throws(()=>parseModelJson({callId:7,content:'not json'},{store:{updateModelCall(id,value){updates.push({id,value});}},label:'测试'}),(error)=>error.code===MODEL_JSON_ERROR_CODES.INVALID);assert.equal(updates[0].value.status,'invalid_output');assert.match(updates[0].value.error,/MODEL_JSON_INVALID/);});
test('结构修复最多调用一次并返回统一结果',async()=>{let repairs=0;const parsed=await parseModelJsonWithRepair({content:'bad'},{label:'测试',repair:async()=>{repairs+=1;return {content:'```json\n{"fixed":true}\n```'};}});assert.deepEqual(parsed,{fixed:true});assert.equal(repairs,1);repairs=0;await assert.rejects(()=>parseModelJsonWithRepair({content:'bad'},{label:'测试',repair:async()=>{repairs+=1;return {content:'still bad'};}}),(error)=>error.code===MODEL_JSON_ERROR_CODES.REPAIR_FAILED);assert.equal(repairs,1);});
test('结构修复允许按次数把具体失败反馈继续交给模型',async()=>{let repairs=0;const parsed=await parseModelJsonWithRepair({content:'bad'},{label:'测试',maxRepairAttempts:2,repair:async(error,{attempt,maxAttempts})=>{repairs+=1;assert.equal(error.code,'MODEL_JSON_INVALID');assert.equal(attempt,repairs);assert.equal(maxAttempts,2);return repairs===1?{content:'still bad'}:{content:'{"fixed":true}'};}});assert.deepEqual(parsed,{fixed:true});assert.equal(repairs,2);});
test('工具请求只缺最外层右花括号时可确定性补全',()=>{const raw='{"type":"tool_requests","assistant_note":"写 CSS","requests":[{"requestId":"tr_css","capability":"filesystem.project.write","arguments":{"mode":"set_head","content":"<style>.page{color:#fff}</style>"},"reason":"写入"}]';const parsed=parseModelJson({content:raw,finishReason:'length'},{label:'CSS Agent'});assert.equal(parsed.type,'tool_requests');assert.equal(parsed.requests[0].arguments.mode,'set_head');});
test('工具请求缺少请求对象右花括号时可确定性补全',()=>{const raw='{"type":"tool_requests","assistant_note":"追加 HTML","requests":[{"requestId":"tr_visual","capability":"filesystem.project.document_write","arguments":{"operation":"append","content":"<style>.x{}</style>"},"reason":"追加"]}' ;const parsed=parseModelJson({content:raw,finishReason:'length'},{label:'AI 视觉 Agent'});assert.equal(parsed.type,'tool_requests');assert.equal(parsed.requests[0].arguments.operation,'append');});
test('AI 视觉分块请求缺 reason 但只缺尾部括号时可先恢复再由入口补齐',()=>{const raw='{"type":"tool_requests","assistant_note":"写入主题 CSS 与通用骨架","requests":[{"requestId":"tr_visual_append_3","capability":"filesystem.project.document_write","arguments":{"resourceId":"project:current","path":"ai-beautified.html","operation":"append","sessionId":"ai-visual-test","expectedRevision":0,"content":"</body>\\n"}]}' ;const parsed=parseModelJson({content:raw,finishReason:'length'},{label:'AI 视觉 Agent',allowMissingToolRequestReason:true});assert.equal(parsed.type,'tool_requests');assert.equal(parsed.requests[0].reason,undefined);assert.equal(parsed.requests[0].arguments.content,'</body>\n');});
test('AI 视觉分块请求缺 assistant_note 和 reason 但只缺尾部括号时仍可先恢复',()=>{const raw='{"type":"tool_requests","requests":[{"requestId":"tr_visual_append_4","capability":"filesystem.project.document_write","arguments":{"operation":"append","content":"</body>\\n"}]}' ;const parsed=parseModelJson({content:raw,finishReason:'length'},{label:'AI 视觉 Agent',allowMissingToolRequestReason:true,allowMissingToolRequestAssistantNote:true});assert.equal(parsed.type,'tool_requests');assert.equal('assistant_note' in parsed,false);assert.equal('reason' in parsed.requests[0],false);});
test('JSON 尾部字段缺失或字符串截断时不执行程序修复',()=>{
  assert.equal(repairJsonSyntaxOnly('{"type":"tool_requests","assistant_note":"写入","requests":[{"requestId":"tr_1","capability":"filesystem.project.document_write","arguments":{}}]'), null);
  assert.equal(repairJsonSyntaxOnly('{"type":"tool_requests","assistant_note":"写入","requests":[{"requestId":"tr_1","capability":"filesystem.project.document_write","arguments":{"content":"<style>') , null);
});
