import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertPublicPageUrl } from '../declarative-web-page/collector.mjs';

const PROFILE=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
function browserExecutable(){return [process.env.PUPPETEER_EXECUTABLE_PATH,process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'Google','Chrome','Application','chrome.exe'),process.env['ProgramFiles(x86)']&&path.join(process.env['ProgramFiles(x86)'],'Google','Chrome','Application','chrome.exe'),process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,'Google','Chrome','Application','chrome.exe')].filter(Boolean).find((item)=>fs.existsSync(item))||'';}
export function normalizeBrowserPageConfig(input={}){const profileId=String(input.profileId||'default').trim();if(!PROFILE.test(profileId))throw new Error('浏览器 Profile ID 必须使用 kebab-case');const declared=Array.isArray(input.actions)?input.actions:[...(input.clickSelector?[{type:'click',selector:input.clickSelector}]:[]),...(input.typeSelector?[{type:'type',selector:input.typeSelector,value:input.typeValue}]:[]),...(Number(input.waitMilliseconds)>0?[{type:'wait',milliseconds:input.waitMilliseconds}]:[])];if(declared.length>10)throw new Error('浏览器动作不能超过 10 个');return {...input,profileId,waitForSelector:String(input.waitForSelector||'').trim(),loginSelector:String(input.loginSelector||'').trim(),actions:declared.map((action)=>{if(!['click','type','wait'].includes(action?.type))throw new Error('浏览器动作只支持 click、type、wait');if(action.type!=='wait'&&!String(action.selector||'').trim())throw new Error('浏览器动作缺少 selector');return {type:action.type,selector:String(action.selector||'').trim(),value:String(action.value||'').slice(0,1000),milliseconds:Math.min(5000,Math.max(0,Number(action.milliseconds)||0))};})};}
export function browserProfileDirectory(root,pluginId,profileId){const base=path.resolve(root,'data','browser-profiles'),target=path.resolve(base,pluginId,profileId);if(!target.startsWith(`${base}${path.sep}`))throw new Error('浏览器 Profile 路径越界');return target;}
export async function renderBrowserPageHtml(url,{root,profileId='default',timeoutMs=60000,dnsLookup,spawnImpl=spawn}={}){await assertPublicPageUrl(url,dnsLookup);const profileDir=browserProfileDirectory(root,'browser-web-page',profileId);fs.mkdirSync(profileDir,{recursive:true});const worker=fileURLToPath(new URL('./worker.mjs',import.meta.url)),payload=Buffer.from(JSON.stringify({url,profileId,profileDir,analysisMode:true,analysisWaitMs:2500})).toString('base64url');return new Promise((resolve,reject)=>{const child=spawnImpl(process.execPath,[worker,payload],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{SystemRoot:process.env.SystemRoot||'',TEMP:process.env.TEMP||'',TMP:process.env.TMP||'',PATH:process.env.PATH||'',PUPPETEER_CACHE_DIR:process.env.PUPPETEER_CACHE_DIR||'',PUPPETEER_EXECUTABLE_PATH:browserExecutable()}});let stdout='',stderr='',settled=false;const timer=setTimeout(()=>{if(settled)return;settled=true;child.kill('SIGKILL');reject(Object.assign(new Error('动态页面分析超时'),{code:'TIMEOUT'}));},timeoutMs);child.stdout.on('data',(chunk)=>{stdout+=chunk;if(stdout.length>3_000_000)child.kill('SIGKILL');});child.stderr.on('data',(chunk)=>{stderr+=chunk;if(stderr.length>20000)stderr=stderr.slice(-20000);});child.on('error',(error)=>{if(settled)return;settled=true;clearTimeout(timer);reject(error);});child.on('exit',(code)=>{if(settled)return;settled=true;clearTimeout(timer);if(code!==0){let detail;try{detail=JSON.parse(stderr.trim().split(/\r?\n/).at(-1));}catch{}reject(Object.assign(new Error(detail?.message||stderr.trim()||`动态页面分析进程退出：${code}`),{code:detail?.code||'NETWORK_ERROR'}));return;}try{resolve(JSON.parse(stdout));}catch{reject(new Error('动态页面分析返回无效结果'));}});});}
export async function runBrowserPageCollector(config,{root,pluginId='browser-web-page',timeoutMs=60000,dnsLookup,spawnImpl=spawn}={}){const normalized=normalizeBrowserPageConfig(config);await assertPublicPageUrl(normalized.url,dnsLookup);const profileDir=browserProfileDirectory(root,pluginId,normalized.profileId);fs.mkdirSync(profileDir,{recursive:true});const worker=fileURLToPath(new URL('./worker.mjs',import.meta.url));const payload=Buffer.from(JSON.stringify({...normalized,profileDir})).toString('base64url');return new Promise((resolve,reject)=>{const child=spawnImpl(process.execPath,[worker,payload],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{SystemRoot:process.env.SystemRoot||'',TEMP:process.env.TEMP||'',TMP:process.env.TMP||'',PATH:process.env.PATH||'',PUPPETEER_CACHE_DIR:process.env.PUPPETEER_CACHE_DIR||'',PUPPETEER_EXECUTABLE_PATH:browserExecutable()}});let stdout='',stderr='',settled=false;const timer=setTimeout(()=>{if(settled)return;settled=true;child.kill('SIGKILL');reject(Object.assign(new Error('浏览器采集超过硬超时，子进程已终止'),{code:'TIMEOUT'}));},Math.min(120000,Math.max(5000,timeoutMs)));child.stdout.on('data',(chunk)=>{stdout+=chunk;if(stdout.length>2_000_000){child.kill('SIGKILL');}});child.stderr.on('data',(chunk)=>{stderr+=chunk;if(stderr.length>20000)stderr=stderr.slice(-20000);});child.on('error',(error)=>{if(settled)return;settled=true;clearTimeout(timer);reject(error);});child.on('exit',(code)=>{if(settled)return;settled=true;clearTimeout(timer);if(code!==0){let detail;try{detail=JSON.parse(stderr.trim().split(/\r?\n/).at(-1));}catch{}const error=Object.assign(new Error(detail?.message||stderr.trim()||`浏览器子进程退出：${code}`),{code:detail?.code||'NETWORK_ERROR'});reject(error);return;}try{resolve(JSON.parse(stdout));}catch{reject(new Error('浏览器子进程返回无效结果'));}});});}
