import crypto from 'node:crypto';
import { planRepoDiscoveryQueries, filterRepositoriesByInterest } from '../llm/repo-discovery.mjs';
import { getAccountContext } from '../domain/account-context.mjs';
import { filterCollectedItems } from '../domain/collection-quality.mjs';
import { syncLegacyCollectionSources } from '../collectors/legacy-source-adapter.mjs';
import { createCollectorRuntime } from '../collectors/runtime-registry.mjs';
import { createBuiltinCollectorRegistry } from '../collectors/builtin-registry.mjs';
import { createStoreCollectionRunner } from '../collectors/store-runner.mjs';
import { ExtensionConfigurationService } from '../extensions/configuration-service.mjs';

export class JobManager {
  constructor(store,config,modelsResolver=null){this.store=store;this.config=config;this.modelsResolver=modelsResolver;this.jobs=new Map();}
  startCollection(batchId,sources,maxAgeHours=null){if(!this.store.getBatch(batchId))throw new Error('批次不存在');const running=[...this.jobs.values()].find((job)=>job.batchId===batchId&&job.status==='running');if(running)return running;const job={id:crypto.randomUUID(),batchId,type:'collect',sources,maxAgeHours,status:'running',progress:'准备采集',logs:[],createdAt:new Date().toISOString()};this.jobs.set(job.id,job);this.runCollection(job).catch(()=>{});return job;}
  log(job,message){job.progress=message;job.logs.push({at:new Date().toISOString(),message});if(job.logs.length>200)job.logs.shift();}
  async #githubQueries(job){const service=new ExtensionConfigurationService({root:this.config.workspaceRoot,repository:this.store.repositories.extensionSettings});const manifest=createBuiltinCollectorRegistry().getManifest('github-discovery-collector');const effective=service.resolve({extensionType:'collector',extensionId:manifest.id,manifest}).values;const aiCfg={enabled:effective.aiQueriesEnabled,refreshDays:effective.refreshDays,maxQueries:effective.maxQueries,perQueryLimit:effective.perQueryLimit,relevanceFilter:effective.relevanceFilter,minInterestScore:effective.minInterestScore};const gateway=typeof this.modelsResolver==='function'?this.modelsResolver():null;if(!job.sources.includes('github')||aiCfg.enabled===false||!gateway)return {queries:[],gateway,aiCfg};const planned=await planRepoDiscoveryQueries({workspaceRoot:this.config.workspaceRoot,gateway,accountContext:getAccountContext(),refreshDays:Number(aiCfg.refreshDays||7),maxQueries:Number(aiCfg.maxQueries||6),log:(message)=>this.log(job,message)});return {queries:(planned.queries||[]).map((query)=>({...query,limit:Number(aiCfg.perQueryLimit||15)})),gateway,aiCfg};}
  async runCollection(job){
    this.store.updateBatch(job.batchId,{status:'running',stage:'collect'});syncLegacyCollectionSources(this.config,this.store.repositories.collectionSources);
    const sourceTypes=[];if(job.sources.includes('reddit'))sourceTypes.push('reddit');if(job.sources.includes('rsshub'))sourceTypes.push('rsshub','twitter','direct',...this.store.listCollectionSources().map((item)=>item.source_type).filter((item)=>!['reddit','rsshub','twitter','direct','github'].includes(item)));if(job.sources.includes('github'))sourceTypes.push('github');
    const topRuns=new Map(job.sources.map((source)=>[source,this.store.startSourceRun(job.batchId,source)]));for(const source of job.sources)this.log(job,`开始采集 ${source}`);
    try{
      const {queries,gateway,aiCfg}=await this.#githubQueries(job);
      const configuration=new ExtensionConfigurationService({root:this.config.workspaceRoot,repository:this.store.repositories.extensionSettings});const registry=await createCollectorRuntime({root:this.config.workspaceRoot,config:this.config,onProgress:(message)=>this.log(job,message),githubQueries:queries,configurationResolver:(manifest)=>configuration.resolve({extensionType:'collector',extensionId:manifest.id,manifest})});const runner=createStoreCollectionRunner({store:this.store,registry});const run=await runner.run({batchId:job.batchId,sourceTypes:[...new Set(sourceTypes)],limits:{maxItems:100}});
      const quality=filterCollectedItems(run.items);if(quality.dropped.length)this.log(job,`采集质量过滤：丢弃 ${quality.dropped.length} 条标题和正文均为空的记录`);let filtered=quality.kept;
      if(queries.length&&aiCfg.relevanceFilter!==false&&gateway){const aiRepos=filtered.filter((item)=>item.sourceGroup==='github'&&(item.discoveryChannels||[]).includes('ai-search'));if(aiRepos.length){const kept=await filterRepositoriesByInterest({gateway,accountContext:getAccountContext(),repos:aiRepos,threshold:Number(aiCfg.minInterestScore||6),log:(message)=>this.log(job,message)});const keep=new Map(kept.map((item)=>[String(item.repository||'').toLowerCase(),item]));filtered=filtered.map((item)=>item.sourceGroup==='github'&&(item.discoveryChannels||[]).includes('ai-search')?(keep.get(String(item.repository||'').toLowerCase())||((item.discoveryChannels||[]).some((channel)=>channel!=='ai-search')?item:null)):item).filter(Boolean);}}
      for(const source of job.sources){const selected=filtered.filter((item)=>source==='reddit'?item.sourceGroup==='reddit':source==='github'?item.sourceGroup==='github':!['reddit','github'].includes(item.sourceGroup));const sourceResults=run.results.filter((item)=>source==='reddit'?item.sourceType==='reddit':source==='github'?item.sourceType==='github':!['reddit','github'].includes(item.sourceType));const success=sourceResults.some((item)=>item.status==='ok');this.store.addHotspots(job.batchId,source,selected);this.store.finishSourceRun(topRuns.get(source),success?'success':'failed',selected.length,success?null:'所有具体来源均采集失败');this.log(job,`${source} ${success?'完成':'失败'}，共 ${selected.length} 条`);}
      const successes=job.sources.filter((source)=>this.store.getSourceRun(topRuns.get(source))?.status==='success').length;job.status=successes?'completed':'failed';job.finishedAt=new Date().toISOString();this.store.updateBatch(job.batchId,{status:successes?'review':'blocked',stage:successes?'synthesis':'collect'});
    }catch(error){for(const source of job.sources)this.store.finishSourceRun(topRuns.get(source),'failed',0,error.message);this.log(job,`采集失败：${error.message}`);job.status='failed';job.finishedAt=new Date().toISOString();this.store.updateBatch(job.batchId,{status:'blocked',stage:'collect'});}
  }
  get(id){return this.jobs.get(id)||null;}
}
