import { validateSourceConfiguration } from '../../../platform/collectors/contracts.mjs';
import crypto from 'node:crypto';

function reddit(value){const text=String(value||'').trim();const match=text.match(/^(?:https?:\/\/(?:www\.)?reddit\.com\/)?(?:r\/)?([A-Za-z0-9_]{2,21})(?:[/?#].*)?$/i);if(!match)throw new Error('请输入有效的 Reddit 分区，例如 programming、r/programming 或完整 URL');return match[1];}
function route(value){const text=String(value||'').trim();if(!text.startsWith('/')||text.startsWith('//'))throw new Error('RSSHub 路由必须以单个 / 开头');return text.includes('limit=')?text:`${text}${text.includes('?')?'&':'?'}limit=30`;}
function url(value){const parsed=new URL(String(value||'').trim());if(!['http:','https:'].includes(parsed.protocol))throw new Error('只支持 HTTP/HTTPS URL');return parsed.href;}
export function sourceInputForPlugin(pluginId,input={}){
  if(pluginId==='reddit-collector'){const subreddit=reddit(input.subreddit||input.value);return {sourceType:'reddit',sourceKey:`reddit:r/${subreddit}`,label:String(input.label||`r/${subreddit}`).trim(),config:{subreddit,sort:input.sort||'hot',limit:Number(input.limit)||15}};}
  if(pluginId==='feed-collector'){const feedUrl=url(input.url||input.value);return {sourceType:'direct',sourceKey:`direct:${feedUrl}`,label:String(input.label||new URL(feedUrl).hostname).trim(),config:{url:feedUrl}};}
  if(pluginId==='rsshub-collector'){const normalized=route(input.route||input.value);const identity=normalized.replace(/([?&])limit=\d+(?:&|$)/i,'$1').replace(/[?&]$/,'');const twitter=/^\/twitter\/user\//i.test(identity);return {sourceType:twitter?'twitter':'rsshub',sourceKey:`${twitter?'twitter':'rsshub'}:${identity}`,label:String(input.label||identity).trim(),config:{route:normalized}};}
  if(pluginId==='declarative-web-page'){const pageUrl=url(input.url||input.value);const config={url:pageUrl,itemSelector:String(input.itemSelector||'').trim(),titleSelector:String(input.titleSelector||'').trim(),linkSelector:String(input.linkSelector||'').trim(),linkAttribute:String(input.linkAttribute||'href').trim(),summarySelector:String(input.summarySelector||'').trim(),authorSelector:String(input.authorSelector||'').trim(),dateSelector:String(input.dateSelector||'').trim(),dateAttribute:String(input.dateAttribute||'datetime').trim(),nextPageSelector:String(input.nextPageSelector||'').trim(),maxPages:Number(input.maxPages)||1,limit:Number(input.limit)||30};return {sourceType:'web-page',sourceKey:`web-page:${pageUrl}`,label:String(input.label||new URL(pageUrl).hostname).trim(),config};}
  if(pluginId==='browser-web-page'){const pageUrl=url(input.url||input.value),click=String(input.clickSelector||'').trim(),typeSelector=String(input.typeSelector||'').trim(),wait=Number(input.waitMilliseconds)||0;const config={url:pageUrl,profileId:String(input.profileId||'default').trim(),waitForSelector:String(input.waitForSelector||'').trim(),clickSelector:click,typeSelector,typeValue:String(input.typeValue||''),waitMilliseconds:wait,loginSelector:String(input.loginSelector||'').trim(),itemSelector:String(input.itemSelector||'').trim(),titleSelector:String(input.titleSelector||'').trim(),linkSelector:String(input.linkSelector||'').trim(),linkAttribute:String(input.linkAttribute||'href').trim(),summarySelector:String(input.summarySelector||'').trim(),authorSelector:String(input.authorSelector||'').trim(),dateSelector:String(input.dateSelector||'').trim(),dateAttribute:String(input.dateAttribute||'datetime').trim(),limit:Number(input.limit)||30};return {sourceType:'browser-page',sourceKey:`browser-page:${pageUrl}:${config.profileId}`,label:String(input.label||new URL(pageUrl).hostname).trim(),config};}
  const config={...input};delete config.label;delete config.value;const identity=crypto.createHash('sha256').update(JSON.stringify(config,Object.keys(config).sort())).digest('hex').slice(0,24);return {sourceType:String(input.sourceType||'plugin-source'),sourceKey:`plugin:${pluginId}:${identity}`,label:String(input.label||pluginId).trim(),config};
}
export class CollectionSourceService{
  constructor({repository,registry}){this.repository=repository;this.registry=registry;}
  create(input){const plugin=this.registry.get(input.pluginId);if(!plugin)throw new Error('采集插件不存在');const normalized=sourceInputForPlugin(input.pluginId,{...(input.config||input),label:input.label||(input.config||{}).label,sourceType:plugin.manifest.collector.sourceTypes[0]});const issues=validateSourceConfiguration(plugin.manifest,normalized.config);if(issues.length)throw new Error(issues[0].message);if(this.repository.getByKey(normalized.sourceKey))throw new Error('这个采集源已经存在');return this.repository.upsert({pluginId:plugin.manifest.id,pluginVersion:plugin.manifest.version,...normalized,enabled:input.enabled!==false,origin:'unified-api'});}
  update(id,input){const current=this.repository.get(id);if(!current)throw new Error('采集源不存在');const pluginId=input.pluginId||current.plugin_id;const plugin=this.registry.get(pluginId);if(!plugin)throw new Error('采集插件不存在');const normalized=sourceInputForPlugin(pluginId,{...current.config,...(input.config||{}),label:input.label||current.label});const duplicate=this.repository.getByKey(normalized.sourceKey);if(duplicate&&duplicate.id!==current.id)throw new Error('这个采集源已经存在');return this.repository.update(id,{pluginId,pluginVersion:plugin.manifest.version,...normalized,enabled:input.enabled??current.enabled});}
}
