import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { APP_VERSION } from '../version.mjs';
import { validateCollectorManifest } from './contracts.mjs';
import { assertSafeRemoteUrl } from '../tools/remote-adapter.mjs';

const MAX_FILES=100,MAX_BYTES=10_000_000,EXTENSIONS=new Set(['.mjs','.json','.md','.txt']);
const paths=(root)=>({installed:path.join(root,'data','installed-collector-plugins'),catalog:path.join(root,'data','collector-plugins.json'),events:path.join(root,'data','collector-plugin-events.jsonl')});
const inside=(candidate,root)=>{const relative=path.relative(path.resolve(root),path.resolve(candidate));return relative===''||(!relative.startsWith('..')&&!path.isAbsolute(relative));};
function tuple(value){return String(value).match(/(\d+)\.(\d+)\.(\d+)/)?.slice(1).map(Number)||null;}
function compatible(range){const current=tuple(APP_VERSION),minimum=tuple(range);if(!current||!minimum)return false;for(let i=0;i<3;i++){if(current[i]>minimum[i])return true;if(current[i]<minimum[i])return false;}return true;}
function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=`${file}.${process.pid}.tmp`;fs.writeFileSync(temp,`${JSON.stringify(value,null,2)}\n`);fs.renameSync(temp,file);}
function record(root,input){const file=paths(root).events;fs.mkdirSync(path.dirname(file),{recursive:true});fs.appendFileSync(file,`${JSON.stringify({createdAt:new Date().toISOString(),...input})}\n`);}
export function readCollectorPluginCatalog(root){if(!fs.existsSync(paths(root).catalog))return {schemaVersion:1,plugins:{}};const value=JSON.parse(fs.readFileSync(paths(root).catalog,'utf8'));if(value.schemaVersion!==1||!value.plugins)throw new Error('采集插件目录无效');return value;}
function walk(root){const files=[];function visit(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isSymbolicLink())throw new Error('采集插件禁止符号链接');if(entry.isDirectory())visit(file);else if(entry.isFile())files.push(file);}}visit(root);return files;}
function permissions(manifest){const value=manifest.permissions;if(!value||!Array.isArray(value.networkDomains)||!Array.isArray(value.pathAccess)||!Array.isArray(value.credentials)||typeof value.externalWrite!=='boolean')throw new Error('采集插件 permissions 无效');if(value.pathAccess.length||value.externalWrite)throw new Error('采集插件不得声明本地路径或外部写入权限');for(const domain of value.networkDomains)if(!/^[a-z0-9.-]+$/i.test(domain)||domain==='localhost')throw new Error(`非法网络域名：${domain}`);}
export function validateCollectorPluginDirectory(directory){const root=fs.realpathSync.native(path.resolve(directory)),files=walk(root);if(!files.length||files.length>MAX_FILES)throw new Error('采集插件文件数量超限');let size=0;for(const file of files){if(!inside(file,root)||!EXTENSIONS.has(path.extname(file)))throw new Error(`不允许的插件文件：${path.basename(file)}`);size+=fs.statSync(file).size;}if(size>MAX_BYTES)throw new Error('采集插件包超过大小限制');const manifestFile=path.join(root,'manifest.json');if(!fs.existsSync(manifestFile))throw new Error('采集插件缺少 manifest.json');const manifest=JSON.parse(fs.readFileSync(manifestFile,'utf8'));const issues=validateCollectorManifest(manifest);if(issues.length)throw new Error(`采集插件 Manifest 无效：${issues[0].message}`);if(!['local-collector','remote-collector'].includes(manifest.type))throw new Error('采集插件 type 无效');if(!compatible(manifest.compatibleApp))throw new Error(`插件需要 ${manifest.compatibleApp}，当前工作台为 ${APP_VERSION}`);permissions(manifest);
  if(manifest.type==='local-collector'){const entry=path.resolve(root,manifest.entry||'');if(!inside(entry,root)||path.extname(entry)!=='.mjs'||!fs.existsSync(entry))throw new Error('本地采集插件 entry 无效');for(const file of files.filter((item)=>path.extname(item)==='.mjs'))for(const match of fs.readFileSync(file,'utf8').matchAll(/(?:from\s*|import\s*\(|^\s*import\s*)\s*['"]([^'"]+)['"]/gm)){const spec=match[1];if(spec.startsWith('node:'))continue;if(!spec.startsWith('.')||!inside(path.resolve(path.dirname(file),spec),root))throw new Error(`采集插件 import 越界：${spec}`);}}
  else{const endpoint=new URL(manifest.endpoint);if(endpoint.protocol!=='https:'||endpoint.username||endpoint.password||!manifest.permissions.networkDomains.includes(endpoint.hostname.toLowerCase()))throw new Error('远程采集端点必须是已授权的 HTTPS 域名');}
  const digest=crypto.createHash('sha256');for(const file of [...files].sort()){digest.update(path.relative(root,file));digest.update(fs.readFileSync(file));}return {directory:root,manifest,files:files.map((file)=>path.relative(root,file)),contentHash:`sha256:${digest.digest('hex')}`};}
export function installCollectorPlugin(root,directory,builtinIds=[]){const checked=validateCollectorPluginDirectory(directory),{id}=checked.manifest;if(builtinIds.includes(id))throw new Error(`采集插件 ID 与内置实现冲突：${id}`);const catalog=readCollectorPluginCatalog(root),target=path.join(paths(root).installed,id);if(fs.existsSync(target))fs.rmSync(target,{recursive:true,force:true});for(const relative of checked.files){const destination=path.join(target,relative);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.copyFileSync(path.join(checked.directory,relative),destination);}const item={id,name:checked.manifest.name,version:checked.manifest.version,status:'disabled',firstRunConfirmedAt:'',manifest:checked.manifest,contentHash:checked.contentHash,installedAt:new Date().toISOString()};catalog.plugins[id]=item;atomic(paths(root).catalog,catalog);record(root,{pluginId:id,action:'install',result:'ok'});return item;}
export function setCollectorPluginStatus(root,id,status){if(!['enabled','disabled'].includes(status))throw new Error('采集插件状态无效');const catalog=readCollectorPluginCatalog(root),item=catalog.plugins[id];if(!item||item.status==='uninstalled')throw new Error('采集插件不存在');item.status=status;item.updatedAt=new Date().toISOString();atomic(paths(root).catalog,catalog);record(root,{pluginId:id,action:status,result:'ok'});return item;}
export function confirmCollectorPluginFirstRun(root,id){const catalog=readCollectorPluginCatalog(root),item=catalog.plugins[id];if(!item||item.status==='uninstalled')throw new Error('采集插件不存在');item.firstRunConfirmedAt||=new Date().toISOString();atomic(paths(root).catalog,catalog);record(root,{pluginId:id,action:'first-run-confirm',result:'ok'});return item;}
export function uninstallCollectorPlugin(root,id){const catalog=readCollectorPluginCatalog(root),item=catalog.plugins[id];if(!item||item.status==='uninstalled')throw new Error('采集插件不存在');item.status='uninstalled';item.updatedAt=new Date().toISOString();atomic(paths(root).catalog,catalog);record(root,{pluginId:id,action:'uninstall',result:'ok'});return item;}
export function listCollectorPluginEvents(root,limit=100){const file=paths(root).events;if(!fs.existsSync(file))return [];return fs.readFileSync(file,'utf8').trim().split(/\r?\n/).filter(Boolean).slice(-Math.min(500,limit)).reverse().map(JSON.parse);}
async function remoteAdapter(root,item,dependencies={}){const execute=async(config)=>{const current=readCollectorPluginCatalog(root).plugins[item.id];if(!current?.firstRunConfirmedAt)throw Object.assign(new Error('远程采集插件首次执行前需要确认权限'),{code:'AUTH_REQUIRED'});await assertSafeRemoteUrl(item.manifest.endpoint,item.manifest.permissions.networkDomains,dependencies.dnsLookup);const response=await (dependencies.fetchImpl||fetch)(item.manifest.endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({config}),redirect:'error'});if(!response.ok)throw new Error(`远程采集插件返回 HTTP ${response.status}`);const text=await response.text();if(Buffer.byteLength(text)>2_000_000)throw new Error('远程采集响应超过大小限制');return JSON.parse(text);};return {collect:execute,test:async(config)=>{const result=await execute(config);return {ok:true,title:item.name,itemCount:result.items?.length||0,items:(result.items||[]).slice(0,5)};}};}
export async function loadInstalledCollectorPlugins(root,dependencies={}){const result=[];for(const item of Object.values(readCollectorPluginCatalog(root).plugins).filter((entry)=>entry.status==='enabled')){const directory=path.join(paths(root).installed,item.id),checked=validateCollectorPluginDirectory(directory);if(checked.contentHash!==item.contentHash)throw new Error(`采集插件完整性校验失败：${item.id}`);let adapter;if(item.manifest.type==='remote-collector')adapter=await remoteAdapter(root,item,dependencies);else{const module=await import(`${pathToFileURL(path.join(directory,item.manifest.entry)).href}?v=${encodeURIComponent(item.contentHash)}`);if(typeof module.collect!=='function')throw new Error(`采集插件缺少 collect：${item.id}`);adapter={collect:module.collect,test:module.test};}result.push({manifest:item.manifest,adapter});}return result;}
