import dns from 'node:dns/promises';
import { privateIp } from '../../shared/network-safety.mjs';

const VOID=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);
const ENTITIES={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};
function decode(value=''){return String(value).replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi,(_,code)=>code[0]==='#'?(code[1].toLowerCase()==='x'?String.fromCodePoint(parseInt(code.slice(2),16)):String.fromCodePoint(Number(code.slice(1)))):(ENTITIES[code.toLowerCase()]??`&${code};`));}
function attrs(value=''){const result={};for(const match of value.matchAll(/([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g))result[match[1].toLowerCase()]=decode(match[2]??match[3]??match[4]??'');return result;}
export function parseStaticHtml(html){const root={tag:'#root',attrs:{},children:[],parent:null};let current=root;const cleaned=String(html).replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style|template|noscript)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'');
  for(const token of cleaned.matchAll(/<[^>]+>|[^<]+/g)){const value=token[0];if(value.startsWith('</')){const tag=value.slice(2).match(/^\s*([^\s>]+)/)?.[1]?.toLowerCase();while(current!==root&&current.tag!==tag)current=current.parent;if(current!==root)current=current.parent;continue;}if(value.startsWith('<')){if(/^<!|^<\?/.test(value))continue;const match=value.match(/^<\s*([^\s/>]+)([\s\S]*?)\/?\s*>$/);if(!match)continue;const node={tag:match[1].toLowerCase(),attrs:attrs(match[2]),children:[],parent:current};current.children.push(node);if(!VOID.has(node.tag)&&!value.endsWith('/>'))current=node;}else if(value.trim())current.children.push({tag:'#text',text:decode(value),attrs:{},children:[],parent:current});}return root;}
function descendants(node){return node.children.flatMap((child)=>child.tag==='#text'?[]:[child,...descendants(child)]);}
function selectorPart(value){const part={tag:'',id:'',classes:[],attrs:[]};let rest=value.trim();const tag=rest.match(/^[a-z][\w-]*/i);if(tag){part.tag=tag[0].toLowerCase();rest=rest.slice(tag[0].length);}while(rest){let match;if((match=rest.match(/^#([\w-]+)/))){part.id=match[1];rest=rest.slice(match[0].length);}else if((match=rest.match(/^\.([\w-]+)/))){part.classes.push(match[1]);rest=rest.slice(match[0].length);}else if((match=rest.match(/^\[([\w:-]+)(?:\s*=\s*["']?([^\]"']+)["']?)?\]/))){part.attrs.push([match[1].toLowerCase(),match[2]]);rest=rest.slice(match[0].length);}else throw new Error(`不支持的选择器片段：${value}`);}return part;}
function matches(node,part){if(part.tag&&node.tag!==part.tag)return false;if(part.id&&node.attrs.id!==part.id)return false;const classes=String(node.attrs.class||'').split(/\s+/);if(part.classes.some((item)=>!classes.includes(item)))return false;return part.attrs.every(([key,value])=>key in node.attrs&&(value===undefined||node.attrs[key]===value));}
export function selectAll(node,selector){if(!selector||/[>,+~:*]/.test(selector))throw new Error('选择器仅支持标签、类、ID、属性和后代关系');let scope=[node];for(const raw of selector.trim().split(/\s+/)){const part=selectorPart(raw);scope=scope.flatMap(descendants).filter((item)=>matches(item,part));}return [...new Set(scope)];}
export function nodeText(node){return (node.tag==='#text'?node.text:node.children.map(nodeText).join(' ')).replace(/\s+/g,' ').trim();}
function field(node,selector,attribute){const target=selector?selectAll(node,selector)[0]:node;if(!target)return '';return attribute?String(target.attrs[attribute.toLowerCase()]||'').trim():nodeText(target);}
function publicUrl(value){const target=new URL(value);if(!['http:','https:'].includes(target.protocol)||target.username||target.password)throw new Error('只允许无内嵌凭据的 HTTP/HTTPS URL');return target;}
export async function assertPublicPageUrl(value,dnsLookup=dns.lookup){const target=publicUrl(value);const addresses=await dnsLookup(target.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some((item)=>privateIp(item.address)))throw new Error('页面地址解析到本机、内网或保留地址');return target;}
async function readText(response,maxBytes){const type=response.headers.get('content-type')||'';if(!/text\/html|application\/xhtml\+xml/i.test(type))throw new Error('页面响应不是 HTML');const reader=response.body?.getReader();if(!reader)throw new Error('页面响应没有内容');let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new Error('页面响应超过大小限制');}chunks.push(Buffer.from(value));}return Buffer.concat(chunks).toString('utf8');}
export async function fetchPublicPage(value,{fetchImpl=fetch,dnsLookup=dns.lookup,maxBytes=2_000_000,timeoutMs=20_000}={}){let current=publicUrl(value).href;for(let count=0;count<=3;count++){await assertPublicPageUrl(current,dnsLookup);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetchImpl(current,{redirect:'manual',signal:controller.signal,headers:{accept:'text/html,application/xhtml+xml','user-agent':'WriteAssistantCollector/1.0'}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new Error('重定向缺少 Location');current=new URL(location,current).href;continue;}if(!response.ok)throw new Error(`页面返回 HTTP ${response.status}`);return {html:await readText(response,maxBytes),url:current};}finally{clearTimeout(timer);}}throw new Error('页面重定向次数超过限制');}
function date(value){if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?null:parsed.toISOString();}
export function extractPageItems(html,pageUrl,config){const root=parseStaticHtml(html);let nodes;try{nodes=selectAll(root,config.itemSelector);}catch(error){throw Object.assign(error,{code:'INVALID_SOURCE_CONFIG'});}if(!nodes.length)throw Object.assign(new Error(`条目选择器未匹配任何内容：${config.itemSelector}`),{code:'SELECTOR_MISMATCH'});const warnings=[];const items=[];for(const node of nodes){const title=field(node,config.titleSelector);const href=field(node,config.linkSelector,config.linkAttribute||'href');if(!title||!href){warnings.push('跳过缺少标题或链接的匹配项');continue;}let url;try{url=new URL(href,pageUrl).href;}catch{warnings.push(`跳过无效链接：${href}`);continue;}const published=field(node,config.dateSelector,config.dateAttribute||'datetime');items.push({externalId:url,title,url,summary:field(node,config.summarySelector),author:field(node,config.authorSelector),publishedAt:date(published),raw:{sourcePage:pageUrl}});}const unique=[...new Map(items.map((item)=>[item.url,item])).values()];if(!unique.length)throw Object.assign(new Error('选择器匹配到节点，但没有提取出有效标题和链接'),{code:'SELECTOR_MISMATCH'});return {items:unique.slice(0,config.limit||30),warnings,matched:nodes.length};}
export async function collectDeclarativePage(config,dependencies={}){const pages=[];let url=config.url;const maxPages=Math.min(config.maxPages||1,5);for(let index=0;index<maxPages&&url;index++){const page=await fetchPublicPage(url,dependencies);const result=extractPageItems(page.html,page.url,config);pages.push({...result,url:page.url});if(!config.nextPageSelector)break;const root=parseStaticHtml(page.html),next=selectAll(root,config.nextPageSelector)[0];const href=next?.attrs?.href;if(!href)break;url=new URL(href,page.url).href;}const items=[...new Map(pages.flatMap((page)=>page.items).map((item)=>[item.url,item])).values()].slice(0,config.limit||30);return {status:'ok',items,warnings:pages.flatMap((page)=>page.warnings),provenance:{fetchMethod:'static-html',pages:pages.length,matched:pages.reduce((sum,page)=>sum+page.matched,0)}};}
